const StringCrypto = require("string-crypto");
const dotenv = require("dotenv");
dotenv.config();

const requireUser = (user_id) => {
  if (user_id) {
    return;
  } else {
    // If no one is signed in, then forbid access to page
    throw { message: "No user is logged in" };
  }
};

const hashPassword = (username, password) => {
  const encryptPassword = process.env.HASH_ENCRYPT_PASSWORD;
  const { encryptString } = new StringCrypto({
    salt: username,
    iterations: 10,
    digest: "sha256",
  });
  let hashPassword = encryptString(password, encryptPassword);
  return hashPassword;
};

const checkPassword = (username, password, hashPassword) => {
  const encryptPassword = process.env.HASH_ENCRYPT_PASSWORD;
  const { decryptString } = new StringCrypto({
    salt: username,
    iterations: 10,
    digest: "sha256",
  });
  let decryptedString = decryptString(hashPassword, encryptPassword);
  return decryptedString === password;
};

// generated by ChatGPT
const merchantCategoryList = {
  0: {merchant: "Starbucks", category: "Restaurant"},
  1: {merchant: "Walmart", category: "Retail"},
  2: {merchant: "Target", category: "Retail"},
  3: {merchant: "Amazon", category: "Online Retail"},
  4: {merchant: "Costco", category: "Retail"},
  5: {merchant: "Home Depot", category: "Home Improvement"},
  6: {merchant: "Lowe's", category: "Home Improvement"},
  7: {merchant: "Best Buy", category: "Electronics"},
  8: {merchant: "Macy's", category: "Retail"},
  9: {merchant: "Kohl's", category: "Retail"},
  10: {merchant: "CVS Pharmacy", category: "Pharmacy"},
  11: {merchant: "Walgreens", category: "Pharmacy"},
  12: {merchant: "Bank of America", category: "Banking"},
  13: {merchant: "Chase", category: "Banking"},
  14: {merchant: "Wells Fargo", category: "Banking"},
  15: {merchant: "American Airlines", category: "Airline"},
  16: {merchant: "Delta Air Lines", category: "Airline"},
  17: {merchant: "Uber", category: "Rideshare"},
  18: {merchant: "Lyft", category: "Rideshare"},
  19: {merchant: "Netflix", category: "Entertainment"},
  20: {merchant: "Disney+", category: "Entertainment"},
  21: {merchant: "Spotify", category: "Entertainment"},
  22: {merchant: "AT&T", category: "Telecommunications"},
  23: {merchant: "Verizon", category: "Telecommunications"},
  24: {merchant: "Shell", category: "Gas Station"},
  25: {merchant: "ExxonMobil", category: "Gas Station"},
  26: {merchant: "Star Market", category: "Grocery Store"},
  27: {merchant: "Whole Foods Market", category: "Grocery Store"},
  28: {merchant: "Trader Joe's", category: "Grocery Store"},
  29: {merchant: "Safeway", category: "Grocery Store"},
  30: {merchant: "Rite Aid", category: "Pharmacy"},
  31: {merchant: "7-Eleven", category: "Convenience Store"},
  32: {merchant: "Dollar General", category: "Retail"},
  33: {merchant: "Family Dollar", category: "Retail"},
  34: {merchant: "McKesson", category: "Pharmaceutical Distributor"},
  35: {merchant: "Walgreens Boots Alliance", category: "Pharmacy"},
  36: {merchant: "H-E-B", category: "Grocery Store"},
  37: {merchant: "Publix", category: "Grocery Store"},
  38: {merchant: "Sonic Drive-In", category: "Restaurant"},
  39: {merchant: "Popeyes", category: "Restaurant"},
  40: {merchant: "Cricket Wireless", category: "Telecommunications"},
  41: {merchant: "Sprint", category: "Telecommunications"},
  42: {merchant: "T-Mobile", category: "Telecommunications"},
  43: {merchant: "Dairy Queen", category: "Restaurant"},
  44: {merchant: "Jimmy John's", category: "Restaurant"},
  45: {merchant: "Papa John's", category: "Restaurant"},
  46: {merchant: "Dunkin' Donuts", category: "Restaurant"},
  47: {merchant: "Baskin-Robbins", category: "Restaurant"},
  48: {merchant: "Great Clips", category: "Salon"},
  49: {merchant: "Supercuts", category: "Salon"},
  50: {merchant: "Regal Cinemas", category: "Entertainment"},
  51: {merchant: "AMC Theatres", category: "Entertainment"},
  52: {merchant: "McDonald's", category: "Restaurant"},
  53: {merchant: "Subway", category: "Restaurant"},
  54: {merchant: "Burger King", category: "Restaurant"},
  55: {merchant: "Taco Bell", category: "Restaurant"},
  56: {merchant: "Wendy's", category: "Restaurant"},
  57: {merchant: "Pizza Hut", category: "Restaurant"},
  58: {merchant: "Domino's Pizza", category: "Restaurant"},
  59: {merchant: "Chipotle Mexican Grill", category: "Restaurant"},
  60: {merchant: "Panera Bread", category: "Restaurant"},
  61: {merchant: "Olive Garden", category: "Restaurant"},
  62: {merchant: "Outback Steakhouse", category: "Restaurant"},
  63: {merchant: "Applebee's", category: "Restaurant"},
  64: {merchant: "Chili's", category: "Restaurant"},
  65: {merchant: "Red Lobster", category: "Restaurant"},
  66: {merchant: "IHOP", category: "Restaurant"},
  67: {merchant: "Denny's", category: "Restaurant"},
  68: {merchant: "Cracker Barrel", category: "Restaurant"},
  69: {merchant: "Buffalo Wild Wings", category: "Restaurant"},
  70: {merchant: "TGI Fridays", category: "Restaurant"},
  71: {merchant: "Panda Express", category: "Restaurant"},
  72: {merchant: "Five Guys", category: "Restaurant"},
  73: {merchant: "Ikea", category: "Retail"},
  74: {merchant: "World Market", category: "Retail"},
  75: {merchant: "Sam's Club", category: "Retail"},
  76: {merchant: "Steak 'N Shake", category: "Restaurant"},
  77: {merchant: "Menards", category: "Home Improvement"},
  78: {merchant: "Jewel Osco", category: "Grocery Store"},
  79: {merchant: "Mariano's", category: "Grocery Store"},
  80: {merchant: "Nordstrom", category: "Retail"},
  81: {merchant: "Ross Dress For Less", category: "Retail"},
  82: {merchant: "TJ Maxx", category: "Retail"},
  83: {merchant: "Wegman's", category: "Grocery Store"},
  84: {merchant: "Fifth Third Bank", category: "Banking"},
  85: {merchant: "Citi", category: "Banking"},
  86: {merchant: "Alaska Airlines", category: "Airline"},
  87: {merchant: "Southwest Airlines", category: "Airline"},
  88: {merchant: "United Airlines", category: "Airline"},
  89: {merchant: "DoorDash", category: "Retail"},
  90: {merchant: "HBO Max", category: "Entertainment"},
  91: {merchant: "Hulu", category: "Entertainment"},
  92: {merchant: "Paramount+", category: "Entertainment"},
  93: {merchant: "Peacock", category: "Entertainment"},
  94: {merchant: "Xfinity", category: "Telecommunications"},
  95: {merchant: "Sprint", category: "Telecommunications"},
  96: {merchant: "Love's", category: "Gas Station"},
  97: {merchant: "RoadRunner", category: "Gas Station"},
  98: {merchant: "Chevron", category: "Gas Station"},
  99: {merchant: "BP", category: "Gas Station"},
};

const accountChargedList = [
  "Capital One Credit Card",
  "Capital One Debit Card",
  "Checking Account",
  "Savings Account",
  "Citi Debit Card",
  "Citi Credit Card",
  "Chase Debit Card",
  "Chase Credit Card",
  "Corporate Card",
  "American Express Card",
  "Bank of America Debit Card",
  "Bank of America Credit Card",
  "Cash",
  "Wells Fargo Card",
  "Prepaid Debit Card",
  "Discover Card"
];

const getRandomInt = (max) => {
  return Math.floor(Math.random() * max);
};

// Get random date starting from beginning of 2023 until now
const getRandomDate = () => {
  const startDate = new Date("2023-01-01");
  const endDate = new Date();
  const timeDiff = endDate.getTime() - startDate.getTime();
  const randomTime = Math.random() * timeDiff;
  const randomDate = new Date(startDate.getTime() + randomTime);
  return randomDate;
};

module.exports = {
  requireUser,
  hashPassword,
  checkPassword,
  merchantCategoryList,
  accountChargedList,
  getRandomInt,
  getRandomDate,
};